# Generated by Django 6.0.7 on 2026-07-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='address',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='phone',
            field=models.CharField(default='0000000001', max_length=10),
        ),
    ]
